catering_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kitchen/urls.py
from django.urls import path

from kitchen.views import (
    index, CategoryListView,
    CategoryDetailView, CategoryCreateView,
    CategoryUpdateView, CategoryDeleteView,
    CookListView, CookDetailView,
    CookCreateView, CookExperienceUpdateView,
    CookDeleteView, DishListView,
    DishDetailView, DishCreateView,
    DishUpdateView, DishDeleteView,
    assign_or_discharge
)


urlpatterns = [
    path("", index, name="index"),
    path("categories/", CategoryListView.as_view(), name="category-list"),
    path("categories/<int:pk>/", CategoryDetailView.as_view(), name="category-detail"),
    path("categories/create/", CategoryCreateView.as_view(), name="category-create"),
    path("categories/<int:pk>/update/", CategoryUpdateView.as_view(), name="category-update"),
    path("categories/<int:pk>/delete/", CategoryDeleteView.as_view(), name="category-delete"),

    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/experience-update/",
         CookExperienceUpdateView.as_view(), name="experience-update"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),

    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("dishes/<int:pk>/assign-or-discharge/", assign_or_discharge, name="assign-or-discharge"),
]

app_name = "kitchen"

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active" >
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/search.html
{% load crispy_forms_filters %}
<form action="" method="get" class="form-inline">
  {{ search_form|crispy }}
  <input class="btn btn-info" type="submit" value="Search 🔎">
</form>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">User: <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a></li>
    <li class="list-group-item"><a class="sidebar" href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
  {% else %}
    <li class="list-group-item"><a class="sidebar" href="{% url 'login'%}?next={{request.path}}">Login</a></li>
  {% endif %}

  <br>
  <li class="list-group-item"><a class="sidebar" href="{% url 'kitchen:index' %}">Main</a></li>
  <li class="list-group-item"><a class="sidebar" href="{% url 'kitchen:cook-list' %}">Our cooks</a></li>
  <li class="list-group-item"><a class="sidebar" href="{% url 'kitchen:category-list' %}">Food category</a></li>
  <li class="list-group-item"><a class="sidebar" href="{% url 'kitchen:dish-list' %}">Dishes</a></li>
</ul>