catering_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kitchen/urls.py
from django.urls import path

from kitchen.views import (
    index, CategoryListView,
    CategoryDetailView, CategoryCreateView,
    CategoryUpdateView, CategoryDeleteView,
    CookListView, CookDetailView,
    CookCreateView, CookExperienceUpdateView,
    CookDeleteView, DishListView,
    DishDetailView, DishCreateView,
    DishUpdateView, DishDeleteView,
    assign_or_discharge
)


urlpatterns = [
    path("", index, name="index"),
    path("categories/", CategoryListView.as_view(), name="category-list"),
    path("categories/<int:pk>/", CategoryDetailView.as_view(), name="category-detail"),
    path("categories/create/", CategoryCreateView.as_view(), name="category-create"),
    path("categories/<int:pk>/update/", CategoryUpdateView.as_view(), name="category-update"),
    path("categories/<int:pk>/delete/", CategoryDeleteView.as_view(), name="category-delete"),

    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/experience-update/",
         CookExperienceUpdateView.as_view(), name="experience-update"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),

    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("dishes/<int:pk>/assign-or-discharge/", assign_or_discharge, name="assign-or-discharge"),
]

app_name = "kitchen"

kitchen/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="dishes")
    cooks = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="dishes")

    class Meta:
        verbose_name_plural = "dishes"
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("kitchen:dish-detail", kwargs={"pk": self.pk})


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(null=True)

    class Meta:
        verbose_name = "cook"
        verbose_name_plural = "cooks"
        ordering = ["first_name", "last_name"]

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("kitchen:cook-detail", kwargs={"pk": self.pk})

kitchen/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from kitchen.models import Cook, Dish


class ExperienceValidateMixin:
    def clean_years_of_experience(self):
        years_of_experience = self.cleaned_data["years_of_experience"]

        if years_of_experience < 0:
            raise ValidationError(
                "Experience can't be lower then 0"
            )

        if years_of_experience > 50:
            raise ValidationError(
                "Invalid input max value is 50"
            )

        return years_of_experience


class DishPriceValidateMixin:
    def clean_price(self):
        price = self.cleaned_data["price"]

        if price < 0:
            raise ValidationError(
                "We need pay for rent, price can't be lower then 0"
            )
        return price


class CookCreationForm(ExperienceValidateMixin, UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience", "email", "first_name", "last_name",
        )


class CookExperienceUpdateForm(ExperienceValidateMixin, forms.ModelForm):
    class Meta:
        model = Cook
        fields = ("years_of_experience",)


class DishForm(DishPriceValidateMixin, forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Dish
        fields = "__all__"


class SearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name..."})
    )


class UserSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username..."})
    )

kitchen/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from kitchen.forms import CookCreationForm, CookExperienceUpdateForm, DishForm, SearchForm, UserSearchForm
from kitchen.models import Cook, Dish, Category


def index(request):

    num_cooks = Cook.objects.count()
    num_dishes = Dish.objects.count()
    num_categories = Category.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_cooks": num_cooks,
        "num_dishes": num_dishes,
        "num_categories": num_categories,
        "num_visits": num_visits + 1,
    }

    return render(request, "kitchen/index.html", context=context)


class CategoryListView(generic.ListView):
    model = Category
    paginate_by = 5
    queryset = Category.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("username", "")

        context["search_form"] = SearchForm(
            initial={"name": name}
        )

        return context

    def get_queryset(self):
        name = self.request.GET.get("name")

        if name:
            return self.queryset.filter(name__icontains=name)
        return self.queryset


class CategoryDetailView(generic.DetailView):
    model = Category
    queryset = Category.objects.all().prefetch_related("dishes")


class CategoryCreateView(LoginRequiredMixin, generic.CreateView):
    model = Category
    fields = "__all__"
    success_url = reverse_lazy("kitchen:category-list")


class CategoryUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Category
    fields = "__all__"
    success_url = reverse_lazy("kitchen:category-list")


class CategoryDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Category
    success_url = reverse_lazy("kitchen:category-list")


class CookListView(generic.ListView):
    model = Cook
    paginate_by = 5
    queryset = Cook.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")

        context["search_form"] = UserSearchForm(
            initial={"name": name}
        )

        return context

    def get_queryset(self):
        name = self.request.GET.get("name")

        if name:
            return self.queryset.filter(username__icontains=name)
        return self.queryset


class CookDetailView(generic.DetailView):
    model = Cook
    queryset = Cook.objects.prefetch_related("dishes__category")


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = CookCreationForm
    template_name = "kitchen/cook_form.html"


class CookExperienceUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookExperienceUpdateForm


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("kitchen:cook-list")


class DishListView(generic.ListView):
    model = Dish
    paginate_by = 5
    queryset = Dish.objects.select_related("category")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")

        context["search_form"] = SearchForm(
            initial={"name": name}
        )

        return context

    def get_queryset(self):
        name = self.request.GET.get("name")

        if name:
            return self.queryset.filter(name__icontains=name)
        return self.queryset


class DishDetailView(generic.DetailView):
    model = Dish
    queryset = Dish.objects.prefetch_related("cooks")


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = DishForm
    template_name = "kitchen/dish_form.html"


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    queryset = Dish.objects.all()
    form_class = DishForm


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-list")


@login_required
def assign_or_discharge(request, pk):
    dish = Dish.objects.get(pk=pk)
    user = request.user
    if user in dish.cooks.all():
        dish.cooks.remove(user.id)
    else:
        dish.cooks.add(user.id)

    return HttpResponseRedirect(reverse_lazy("kitchen:dish-detail", args=[dish.id]))

templates/kitchen/category_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <p><strong>Do you really want to delete {{ category.name }} from the list?</strong>
  <p><i>All the dishes in this category will be deleted as well</i>

  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes, delete" class="btn btn-danger">
    <a class="btn btn-secondary" href="{% url "kitchen:category-list" %}">No, forget</a>
  </form>
{% endblock %}

templates/kitchen/category_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ category.name }}
  </h1>
  <br>
  {% if category.dishes.all %}
  <ul>
    {% for dish in category.dishes.all %}
      <li><a href="{% url 'kitchen:dish-detail' pk=dish.id %}">{{ dish.name }}</a></li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no dishes in this category yet</p>
  {% endif %}
{% endblock %}

templates/kitchen/category_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} category</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/category_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Category List
      {% if user.is_authenticated %}
    <a style="margin-left: 15px" class="btn btn-primary" href="{% url 'kitchen:category-create' %}">
      Create
    </a>
    {% endif %}
  </h1>
  <br>
  {% include "includes/search.html" %}
  <br>
  {% if category_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        {% if user.is_authenticated %}
          <th>Update</th>
          <th>Delete</th>
        {% endif %}
      </tr>

      {% for category in category_list %}
        <tr>
          <td>
              {{ category.id }}
          </td>
          <td>
            <a href="{% url 'kitchen:category-detail' pk=category.id %}">{{ category.name }}</a>
          </td>
          {% if user.is_authenticated %}
            <td>
                <a href="{% url "kitchen:category-update" pk=category.id %}">Update</a>
            </td>
            <td>
              <a style="color: red" href="{% url "kitchen:category-delete" pk=category.id %}">Delete</a>
            </td>
          {% endif %}
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no categories in the service.</p>
  {% endif %}
{% endblock %}

templates/kitchen/cook_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <p><strong>Do you really want to delete {{ cook.first_name }} {{ cook.last_name }} ?</strong>

  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes, delete" class="btn btn-danger">
    <a class="btn btn-secondary" href="{% url "kitchen:cook-list" %}">No, forget</a>
  </form>
{% endblock %}

templates/kitchen/cook_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ cook.first_name }} {{ cook.last_name }}
  </h1>

  <p><strong>Username:</strong> {{ cook.username }}</p>
  <p><strong>Experience:</strong> {{ cook.years_of_experience }}</p>


  <h4>Dishes</h4>
  <div class="ml-3">


        {% if cook.dishes.all %}
          <table class="table">
            <tr>
              <th>Id</th>
              <th>Name</th>
              <th>Category</th>
            </tr>
            {% for dish in cook.dishes.all %}
              <tr>
                <td>
                  {{ dish.id }}
                </td>
                <td>
                  <a href="{% url 'kitchen:dish-detail' pk=dish.id%}">{{ dish.name }}</a>
                </td>
                <td>
                  <a href="{% url 'kitchen:category-detail' pk=dish.category.id%}">{{ dish.category.name }}</a>
                </td>
              </tr>
            {% endfor %}
          </table>
        {% else %}
          <p>This cook have nothing to offer</p>
        {% endif %}

    {% if user.is_authenticated %}
      <hr>
      <a class="btn btn-secondary" href="{% url 'kitchen:experience-update' pk=cook.id %}">Update experience info</a>
      <a class="btn btn-danger" href="{%  url 'kitchen:cook-delete' pk=cook.id %}">Delete cook</a>
    {% endif %}
  </div>
{% endblock %}

templates/kitchen/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update years of experience,Add new cook" }}</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-success">
  </form>
{% endblock %}

templates/kitchen/cook_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Our cooks:
    {% if user.is_authenticated %}
    <a href="{% url 'kitchen:cook-create' %}" class="btn btn-primary">
      Add new cook
    </a>
    {% endif %}
  </h1>
  <br>
  {% include "includes/search.html" %}
  <br>
  {% if cook_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Username</th>
        <th>Years of experience</th>
        <th>Total dishes</th>
      </tr>

      {% for cook in cook_list %}
        <tr>
          <td>
              {{ cook.id }}
          </td>
          <td>
            <a href="{% url 'kitchen:cook-detail' pk=cook.id %}">{{ cook.first_name }} {{ cook.last_name }}</a>
          </td>
          <td>
            {% if not cook.first_name %}
              <a href="{% url 'kitchen:cook-detail' pk=cook.id %}">{{ cook.username }}</a>
            {% else %}
              {{ cook.username }}
            {% endif %}
          </td>
          <td>
              {{ cook.years_of_experience }}
          </td>
          <td>
            {{ cook.dishes.count }}
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no cooks available in the service.</p>
  {% endif %}
{% endblock %}

templates/kitchen/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <p><strong>Do you really want to delete {{ dish.name }} ?</strong>

  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes, delete" class="btn btn-danger">
    <a class="btn btn-secondary" href="{% url "kitchen:dish-list" %}">No, forget</a>
  </form>
{% endblock %}

templates/kitchen/dish_detail.html
{% extends "base.html" %}

{% block content %}
  <h1 style="padding-top: 10px">
    {{ dish.name }}
  </h1>
  <br>
  <div style="padding-left: 20px">
    <h5>Category: <a href="{% url 'kitchen:category-detail' pk=dish.category.id %}">{{ dish.category.name }}</a></h5>
    <h5>Price: {{ dish.price }} $</h5>
  </div>
  {% if user.is_authenticated %}
    {% if user in dish.cooks.all %}
      <a style="margin-top: 30px" href="{% url 'kitchen:assign-or-discharge' pk=dish.id %}" class="btn btn-danger link-to-page">
        Discharge from this dish
      </a>
    {% else %}
      <a style="margin-top: 30px" href="{% url 'kitchen:assign-or-discharge' pk=dish.id %}" class="btn btn-success link-to-page">
        Assign me to this dish
      </a>
    {% endif %}
  {% endif %}
  <hr>
  <div class="description">
    {{ dish.description }}
  </div>
  <hr>
  Cooks who can prepare:
  {% if dish.cooks.all %}
  <ul>
    {% for cook in dish.cooks.all %}
      <li><a href="{% url 'kitchen:cook-detail' pk=cook.id %}">{{ cook.first_name }} {{ cook.last_name }}</a></li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no cooks who can prepare this dish</p>
  {% endif %}
  {% if user.is_authenticated %}
    <a style="float: left" href="{% url 'kitchen:dish-update' pk=dish.id %}" class="btn btn-secondary link-to-page">
        Update
    </a>
    <a style="margin-left: 15px" href="{% url 'kitchen:dish-delete' pk=dish.id %}" class="btn btn-danger link-to-page">
        Delete
    </a>
  {% endif %}
{% endblock %}

templates/kitchen/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/dish_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Dish list
    {% if user.is_authenticated %}
      <a style="margin-left: 15px" class="btn btn-primary" href="{% url 'kitchen:dish-create' %}">
        add new dish
      </a>
    {% endif %}
  </h1>
  <br>
   {% include "includes/search.html" %}
  <br>
  {% if dish_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Category</th>
        <th>Price</th>
      </tr>

      {% for dish in dish_list %}
        <tr>
          <td>
              {{ dish.id }}
          </td>
          <td>
            <a href="{% url 'kitchen:dish-detail' pk=dish.id %}">{{ dish.name }}</a>
          </td>
          <td>
              {{ dish.category.name }}
          </td>
          <td>
              {{ dish.price }} $
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no dishes in the service.</p>
  {% endif %}
{% endblock %}

templates/kitchen/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Catering service</h1>
  <div class="slogan">
    <p style="text-align: left">Meet your cook,
    <p style="text-align: center">who will
    <p style="text-align: right">cook your meat!
  </div>
  <p>For your event you can pick</p>
  <ul class="index-list">
    <li>from {{ num_cooks }} <strong>cooks</strong> </li>
    <li>choose from {{ num_dishes }} <strong>dishes</strong> </li>
    <li>in {{ num_categories }} <strong>categories</strong> </li>
  </ul>

  <p class="visit-counter">You have visited this page
      {{ num_visits }} time{{ num_visits|pluralize }}.
  </p>

{% endblock %}